name: Build and Publish SiteMesh

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17 with cache
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      #      - name: Setup Gradle
      #        uses: gradle/gradle-build-action@v2
      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
          echo ${GPG_SIGNING_KEY} | base64 -d > ~/.gradle/secring.gpg
      - name: Run build with Gradle Wrapper
        run: ./gradlew assemble test publishToSonatype